use UNIVER;
select au.AUDITORIUM, au.AUDITORIUM_TYPE, au.AUDITORIUM_CAPACITY from
AUDITORIUM au where au.AUDITORIUM in (select TOP(1) aud.AUDITORIUM
from AUDITORIUM aud where au.AUDITORIUM_TYPE = aud.AUDITORIUM_TYPE order by aud.AUDITORIUM_CAPACITY DESC);