use UNIVER;
select a.AUDITORIUM, a.AUDITORIUM_TYPE, a.AUDITORIUM_CAPACITY from
AUDITORIUM a where a.AUDITORIUM_CAPACITY >= all(select au.AUDITORIUM_CAPACITY
from AUDITORIUM au where AUDITORIUM like '%2%');